### ISSUE TITLE
Support unicode characters in keys

### ISSUE THREAD

**Issue by nichochar** [pinterest/pymemcache#122]
It could be a nice feature to be able to support unicode characters in the keys used for the cache. Since ~~the memcached protocol only supports ascii~~, this would require some kind of different approach of preparing keys.

One solution is to use byte arrays, another one would be to use some kind of hashing (murmur hash is probably a good fit here) of the keys, which would entail that we obfuscate them to the user in the middleware.

Useful references:
 - [django uses encoding to bypass this issue](https://github.com/django/django/commit/2679bc0304#diff-c4790c03f34c6a5b2929b8508141831fR73)  
 - [memcached wiki](https://github.com/memcached/memcached/wiki)
 - [convert stuff from binary to ascii library](https://docs.python.org/2/library/binascii.html)
 - [how python-memcached deals with this issue](https://github.com/linsomniac/python-memcached/blob/master/memcache.py#L68-L72)

Key question that remains unclear:
### What are the encoding constrains on memcached keys?
> Keys cannot have spaces, new lines, carriage returns, or null characters.  

Probably the best [answer](http://grokbase.com/t/danga/memcached/07ckzm4pm0/what-is-a-valid-key)

**Comment by jogo** [comment]
memcached supports unicode for both keys and values.  Example run against a local memcached.

So we don't need to do any hashing for unicode keys.

```
$ echo -e 'add my☃ 0 60 11\r\nhello ☃ld\r' | nc localhost 11211
STORED
$ echo -e 'get my☃\r' | nc localhost 11211
VALUE my☃ 0 11
hello ☃ld
END
```

**Comment by nichochar** [comment]
Reading up on it, indeed it seems like the ASCII protocol (which is what we use, since we haven't implemented the binary protocol) supports unicode keys. At least it never says anything otherwise in the docs, and @jogo proves it above.
> The ASCII protocol uses spaces and newlines. Ensure that neither show up your keys, live long and prosper. Binary protocol does not have this issue.

After looking at what other people do:
- django: uses a self written [smart_str](https://github.com/django/django/blob/master/django/utils/encoding.py#L148-L156) function
- python-memcached uses [binascii](https://docs.python.org/2/library/binascii.html) to transcode unicode to ascii using the 32bit checksum hash:
```
def cmemcache_hash(key):
    return (
        (((binascii.crc32(key) & 0xffffffff)
          >> 16) & 0x7fff) or 1)
serverHashFunction = cmemcache_hash
```
Looking at different hashing solutions in [this great stackoverflow answer](http://softwareengineering.stackexchange.com/questions/49550/which-hashing-algorithm-is-best-for-uniqueness-and-speed), and backed up by @smeder 's advice to another Pinterest engineer, the best hashing for this purpose seems to be [murmur hash](https://pypi.python.org/pypi/mmh3/2.2)

I believe it will be easier to use the murmur hash for unicode keys, and do nothing for ascii friendly keys (ideally we modify as little keys as possible, since that prevents debugging and manually making sense of them.

**Comment by nichochar** [comment]
@jogo if we don't hash the keys, it will depend on which encoding is used, and so we are left with the potential of different clients not encoding in the same way. Using a fast hash we guarantee consistent hashing and encoding. Thoughts?

**Comment by nichochar** [comment]
I can't find documentation anywhere saying keys have to be ascii, but I keep seeing it in projects, like this library, or a [golang memcached client](https://github.com/bradfitz/gomemcache/blob/master/memcache/memcache.go#L59)

**Comment by nichochar** [comment]
Thinking about this further, it may be worth not doing anything in the pymemcache client, just to make it's contract more clear, and avoid undesired magic effects.
It's harder to debug a client that hashes some keys and not others, opaquely. 
For this reason, it may be best to continue only supporting ascii keys, and let the applications communicating with the client take care of murmur hashing their keys. 
It might be worth adding a section to the README.
