### ISSUE TITLE
HashClient does not appear to be thread-safe

### ISSUE THREAD

**Issue by jaysoffian** [pinterest/pymemcache#124]
Reading over HashClient, it does not appear to be thread-safe. I'm not clear why it offers the `use_pooling` option which while that providers a thread-safe underlying client, doesn't fix the fact that multiple threads using the same HashClient instance will probably have issues. e.g., looking at `_safely_run_func`, two threads can simultaneously notice the same server in `self._failed_clients` at which point only one thread can win this: `self._failed_clients.pop(client.server)` with the other getting a `KeyError`. (That's just one example... there are several instance variables that are not thread safe).

In fact, the design of HashClient w/r/t to PooledClient seems inside-out. Wouldn't it make more sense for the PooledClient class to create instances of HashClient? [That seems to be what cgordon had in mind](https://github.com/pinterest/pymemcache/pull/35#issuecomment-92590311). Otherwise, it seems that HashClient either needs to have locking added, or one must use an instance per-thread.

Thoughts?

**Comment by cgordon** [comment]
I can't comment on the thread-safety of HashClient, as it has been awhile since I looked at the code (and I have never used Python threads), but I concur that the intention for PooledClient is as @jaysoffian says: PooledClient should manage instances of HashClient, and not vice-versa. In this case my first inclination would be to create a HashPooledClient similar to how PooledClient works. If possible, it would be nice to share some code between those classes.

**Comment by jaysoffian** [comment]
After some more reading, I'm dubious about the design of HashClient. The [memcached docs recommend](https://github.com/memcached/memcached/wiki/ConfiguringClient#failure-or-failover):

> In the dark days of memcached, the default was to always "failover", by trying the next server in the list. That way if a server crashes, its keys will get reassigned to other instances and everything moves on happily. ... Modern life encourages the use of "Failure", when possible. That is, if the server you intend to fetch or store a cache entry to is unavailable, simply proceed as though it was a cache miss.

In my case, I've decided to not bother with HashClient. I'm just going to wrap instances of PooledClient which are chosen using RendezvousHash and not bother with retry logic, adding/removing servers, etc. KISS and all that. I'll revisit this issue when I'm done with that. Minimally, I'll submit a PR updating the docs about thread-safety and this library.

In any case, thanks you for this library I chose it after reading over the code and the base Client is solid.

**Comment by Anakin-Hao** [comment]
Any update on this one?

This issue causes hashclient to return null value when two identical requests are invoked at the same time. It's been given us a lot grief.

**Comment by abhijit-15** [comment]
Can this be considered closed as of v3.2.0?

**Comment by jparise** [comment]
@abhijit-15 is there a specific change that was released that you're thinking of?

**Comment by abhijit-15** [comment]
@jparise Yes. So as of v3.0.0, `use_pooling` has been made available and HashClient sends `encoding` to its pooled clients. IMO even if there are still any issues, the ability to handle custom client classes (for Hash & PooledClient as of v3.2.0) should be sufficient for user to deal with this?

**Comment by jparise** [comment]
That sounds good. Thanks for leaving the detailed comment so others who find this issue will have that additional context.
