### ISSUE TITLE
Drop support for python 3.2

### ISSUE THREAD

**Issue by nichochar** [pinterest/pymemcache#132]
Our build tool has automatically updated pip and virtualenv, and these new versions have dropped support for python 3.2.

Googling around, I have found that a lot of people have dropped support of python 3.0, 3.1 and 3.2. This seems to be a common trend. Here are a few examples:
- [Soco](https://github.com/SoCo/SoCo/issues/324)
- [pip discussion about dropping support](https://groups.google.com/forum/#!topic/pypa-dev/Ef0PF2ZGAv0)
- [python3.2 lifecycle is up february 2017](https://www.python.org/dev/peps/pep-0392/#lifespan)

I vote we drop support, but wanted to get a global view.
@jparise @cgordon any opinions here?

**Comment by jparise** [comment]
I agree. Let's drop it.

**Comment by nichochar** [comment]
Unfortunately, I misunderstood the problem. The question is actually whether we should (temporarily probably) drop support for pypy3. Indeed pypy3 is using a python version of 3.2, and virtualenv and pip have dropped support for it, breaking the CI of pymemcache.

It's a bit of a head scratcher. Ideally I could bump the python pypy3 is using to python 3.3 but I believe support for that isn't yet live. I have asked the pypy folks in IRC about this, but haven't gotten a clear answer yet.

I have a hard time knowing how many people are using the pypy3 version. Maybe we simply remove the test in CI for now, and add it back when the python 3.3 is supported?

**Comment by nichochar** [comment]
Chatting with a guy on the IRC #pypy channel who is having the same issue (I think this may be common), a few notes:
- we suspect _very little_ people are using both python 3.2 and pypy3(.2)
- the best solution is to figure out how to get travis to install the alpha pypy3(.3). Apparently there is a solution using tox-travis [here at jsonschema](https://github.com/Julian/jsonschema/pull/310/files)

**Comment by nichochar** [comment]
Relevant [travic-ci](https://github.com/travis-ci/travis-ci/issues/6304) ticket

**Comment by nichochar** [comment]
After looking into how different people solve this, it seems like the travis folks don't care about supporting pypy3 on different python interpreters. For now, I will deactivate the pypy3 integration testing, following [influx-db-python](https://github.com/gansanay/influxdb-python/commit/68dd91025ac7f8ba27b881d0e126585a33859a5a) and others.
