### ISSUE TITLE
HashClient missing gets_many

### ISSUE THREAD

**Issue by njason** [pinterest/pymemcache#136]
I am looking to use gets_many with HashClient, is this possible?

**Comment by nichochar** [comment]
This is possible, I think you may have a typo, have you tried `get_many` instead of `gets_many` ?

See the code [here](https://github.com/pinterest/pymemcache/blob/master/pymemcache/client/hash.py#L271)

**Comment by njason** [comment]
I am looking for `gets_many` for HashClient, not `get_many`. `gets_many` returns the values and CAS tokens in tuple pairs.

Here is my pull request with `HashClient.gets_many`: https://github.com/pinterest/pymemcache/pull/137
