### ISSUE TITLE
Drop support for python 2.6

### ISSUE THREAD

**Issue by nichochar** [pinterest/pymemcache#139]
We currently support it, but it's in end of life, and a lot of major libraries are dropping support in the near future:
* [pip](https://github.com/pypa/pip/issues/3955)
* [setuptools](https://github.com/pypa/setuptools/issues/878)

It also forces us to use an old version of gevent in our tests, because of the following error:
```
```Collecting gevent (from -r test-requirements.txt (line 4))
  Downloading gevent-1.2.1.tar.gz (2.8MB)
    100% |████████████████████████████████| 2.8MB 510kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-rPyEfW/gevent/setup.py", line 39, in <module>
        raise Exception("Please install gevent 1.1 for Python 2.6")
    Exception: Please install gevent 1.1 for Python 2.6```
```

@jparise @cgordon any thoughts?

**Comment by jparise** [comment]
I agree, especially now that PyPy is 2.7 compatible. Years ago, that was a reason to maintain 2.6 support.

Let's make this change in a minor point release.

**Comment by nichochar** [comment]
Great, I think @jogo also agree, so that settles it, I'll make a PR and make a minor release after https://github.com/pinterest/pymemcache/pull/137 and https://github.com/pinterest/pymemcache/pull/138 go out.
