### ISSUE TITLE
Reopen PR with changes around pickle versions

### ISSUE THREAD

**Issue by nichochar** [pinterest/pymemcache#159]
We reverted a good idea: https://github.com/pinterest/pymemcache/pull/158

The reason of the revert is backwards incompatibility, cc @jogo 

We are still interested in discussing this further though, so I'm opening up this ticket

**Comment by akatrevorjay** [comment]
https://github.com/pinterest/pymemcache/pull/160

**Comment by jparise** [comment]
This can be closed now that #190 has been released.
