### ISSUE TITLE
django support

### ISSUE THREAD

**Issue by ashwin31** [pinterest/pymemcache#176]
how to use it with django, I found substantial performance improvement with this package over the django.core.cache with memcache as backed.

But this failing at some cases. I am looking for any drop in support for django.

**Comment by giantas** [comment]
Just an FYI, did you try out the pointers in the [Best Practices Section](https://pymemcache.readthedocs.io/en/latest/getting_started.html#best-practices)?

**Comment by nichochar** [comment]
> I am looking for any drop in support for django
I don't believe pymemcache should support django, but rather, there should be a django plugin that helps support pymemcache.

Unless I misunderstood your point and there is a feature that this library should implement, I am going to close this ticket (feel free to reopen and clarify).

**Comment by johnthagen** [comment]
For those that stumble upon this issue, https://github.com/django-pymemcache/django-pymemcache
