### ISSUE TITLE
Minor Release 2.x.x ?

### ISSUE THREAD

**Issue by mainanick** [pinterest/pymemcache#200]
Currently am handling a django ticket [`Add support for pymemcache`](https://code.djangoproject.com/ticket/29887) which attempts to  replace [python-memcached](https://github.com/linsomniac/python-memcached) which is [no longer maintained](https://github.com/linsomniac/python-memcached/issues/95) with pymemcache

Issues faced

1. Had to set attribute 'Client' to module pymemcache **resolved on master**
2. disconnect_all servers

Would it be possible to include `disconnect_all` to clients? currently setting it to `quit`

`setattr(pymemcache.Client, "disconnect_all", pymemcache.Client.quit)`

**Comment by jparise** [comment]
We can publish a 2.0.1 release with the package import changes.

> Would it be possible to include `disconnect_all` to clients? currently setting it to `quit`

I'm not exactly sure what you mean. Are you asking if we can provide a client-level function alias for compatibility with python-memcached (per your example)?

If I have that right, I don't think that would be correct. The python-memcached function appears to close _all_ clients, so the more equivalent function would probably be on our `pymemcache.Pool` object.

**Comment by jparise** [comment]
Version 2.1.0 has been released.
