### ISSUE TITLE
key_prefix capabilities of pymemcache

### ISSUE THREAD

**Issue by josyjoy** [pinterest/pymemcache#213]
1) is Key_Prefix is similar concept like tables in other caches like HazelCast, Inginte etc ?
2) whether multiple Key_Prefix use same cache object or different Object  
3)  Is it possible to have any SQL on this cache objects ?

**Comment by jparise** [comment]
> 1. is Key_Prefix is similar concept like tables in other caches like HazelCast, Inginte etc ?

The prefix is a way to namespace keys. Some memcached systems (like [mcrouter](https://github.com/facebook/mcrouter) can apply distribution and routing rules based on key prefixes. I'm not familiar with HazelCast or Inginte so I can't make a direct comparison to them.

> 2. whether multiple Key_Prefix use same cache object or different Object

I think you're asking about storing an object under two different keys (or the same key with two different prefixes). The cache will see those as two distinct objects.

> 3. Is it possible to have any SQL on this cache objects ?

If you're asking if there are SQL-like query capabilities on top of the cache, that isn't something provided by pymemcache (or memcached).
