### ISSUE TITLE
How to get all the keys as a key list using key_prefix?

### ISSUE THREAD

**Issue by josyjoy** [pinterest/pymemcache#215]
1. Can i get all the keys with same key_prefix ?
2. will get_many or get_multi support key_prefix argument as that available in memcache library as 
get(key, namespace=None)
get_multi(keys, key_prefix='', namespace=None)?
3. When will the above feature available with pymemcache?
4.What is the difference between get_many and get_multi?

**Comment by jogo** [comment]
1. I don't think memcache supports this kind of search https://github.com/memcached/memcached/wiki/Commands
2. & 3. We currently do key prefixing in a layer above pymemcache, but would happily accept a patch to support it directly in pymemcache.
4. There is none https://github.com/pinterest/pymemcache/blob/65560b738a01bfd420cdbeaae3b7bd78503c2855/pymemcache/client/base.py#L469
