### ISSUE TITLE
Docs should note that `nodelay=True` can lead to spurious "MemcacheUnknownCommandError"

### ISSUE THREAD

**Issue by sirosen** [pinterest/pymemcache#239]
Porting code which had been using python-memcached to pymemcache, I uncovered an issue in which I was setting a fractional `expire`. (`python-memcached` had hidden this from me entirely, but the bug was there even before.)
However, this was hard to debug because (1) the fractional expiration was never passed by our testsuite (2) I had set `noreply=True` on all `Client.set()` calls, hiding the erroneous expiration.

The result was that I was getting `pymemcache.exceptions.MemcacheUnknownCommandError: b'get'` which was "obviously wrong" and could not reproduce with various tests.
Digging into pymemcache, I saw that these errors are triggered by reading `ERROR` immediately after sending a command, and guessed that an error from a prior command was left in the channel, being read when the `Client.get()` was evaluated.

I'm not sure if there's a better way to handle
```python
from pymemcache.client.base import Client
client = Client(("localhost", 11211))
client.set("foo", "bar", expire=1.5, noreply=True)
client.get("foo")
```

than what's currently being done? It seems reasonable, but I think a documentation warning could save others this same mistake and hassle.

Although this particular case could be handled by checking if `expire` isn't a int, I don't think that's particularly important.

**Comment by cgordon** [comment]
Hi Stephen,

Thank you for the excellent bug report! I was surprised by this behavior, so I went and read back through the protocol documentation:

https://github.com/memcached/memcached/blob/master/doc/protocol.txt

It says this:

> "noreply" optional parameter instructs the server to not send the
>  reply.  NOTE: if the request line is malformed, the server can't
>  parse "noreply" option reliably.  In this case it may send the error
>  to the client, and not reading it on the client side will break
> things.  Client should construct only valid requests.

In light of that, I think the right answer is to validate all the arguments passed and fail immediately if any of them would cause us to construct an invalid request. In this case, that means checking that the value of expire is an integer before serializing it to the request string.

Would you like to send us a PR for that?

Thank you,
Charles

**Comment by sirosen** [comment]
Sure, I'll do that momentarily.

I was thinking that catching this specific kind of malformed request was less important than having some kind of note in the docs that `noreply=True` can "defer errors until the next call to memcache". What do you think of also making a doc change of some kind? I'll keep it separate if I open a PR so that the issues can be reviewed independently.

**Comment by jparise** [comment]
I think that's also a good idea, @sirosen. Thanks!
