### ISSUE TITLE
add() function does not seem to work as documentation implies

### ISSUE THREAD

**Issue by OscarVanL** [pinterest/pymemcache#253]
In Memcached the add() function is supposed to only add if no key with the same name in Memcached already exists. It should return True if it added successfully, or False if it did not add it (because a key with the same name already existed in the cache).

Consider the following code:
```
memcache_client.delete(key="123")
outcome = memcache_client.add(key="123", value="abc")   # Expected: outcome==True
outcome2 = memcache_client.add(key="123", value="abcd")   # Expected: outcome2==False
memcache_client.delete(key="123")
outcome3 = memcache_client.add(key="123", value="abc")   # Expected: outcome3==True
```

We would expect `outcome==True`, `outcome2==False`, `outcome3==True`. The returned values I actually experienced were `outcome==True`, `outcome2==True`, `outcome3==True`.

In order to get add() to work as it should do, I had to write the code as follows:
```
memcache_client.delete(key="123")
outcome = memcache_client.add(key="123", value="abc", noreply=False)   # Expected: outcome==True
outcome2 = memcache_client.add(key="123", value="abcd", noreply=False)   # Expected: outcome2==False
memcache_client.delete(key="123")
outcome3 = memcache_client.add(key="123", value="abc", noreply=False)   # Expected: outcome3==True
```

Now I correctly get `outcome==True`, `outcome2==False`, `outcome3==True`.

In `pymemcache/client/base.py`, the docs for the function add() say:

>         The memcached "add" command.
>         Args:
>           key: str, see class docs for details.
>           value: str, see class docs for details.
>           expire: optional int, number of seconds until the item is expired
>                   from the cache, or zero for no expiry (the default).
>           noreply: optional bool, True to not wait for the reply (defaults to
>                    self.default_noreply).
>           flags: optional int, arbitrary bit field used for server-specific
>                   flags
>         Returns:
>           **If noreply is True, the return value is always True. Otherwise the
>           return value is True if the value was stored, and False if it was
>           not (because the key already existed).**

This implies for me to get the outcome I did for the first section of code I would have to explicitly set `noreply=True`. Infact, even this would be wrong.

The add() function is defined as:

```
def add(self, key, value, expire=0, noreply=None, flags=None):
        if noreply is None:
            noreply = self.default_noreply
```

In order to achieve the expected behaviour this should instead be:

```
def add(self, key, value, expire=0, noreply=False, flags=None):
        if noreply is True:
            noreply = self.default_noreply
```

**Comment by sambrightman** [comment]
I think you are misinterpreting the documentation, which seems clear to me. `default_noreply` is `True` by default on `Client`. So `noreply` becomes `True` by default on most of its methods (those with `noreply=None`). There is additionally a note in the [best practices section](https://pymemcache.readthedocs.io/en/latest/getting_started.html#best-practices) about this.

**Comment by jparise** [comment]
Closing this because @sambrightman does a great job of explaining the current interface.
