### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by mstute** [pinterest/pymemcache#257]
I'm dealing with a production environment where memcached are IPv6 only. The code in _connect assumes IP connections are IPv4 "self.socket_module.AF_INET".

Do you have plans to handle "IPv6 URI", for example: ('inet6:memcache-a', 11211) ?

**Comment by jparise** [comment]
We'd be happy to support IPv6 and would gladly accept a patch that adds that capability.

**Comment by mstute** [comment]
Great, I'll find some resources to handle that.
