### ISSUE TITLE
Add support for TLS

### ISSUE THREAD

**Issue by moisesguimaraes** [pinterest/pymemcache#258]
Since version 1.5.13, Memcached [supports TLS][1].

### Motivation

At [OpenStack][2], we are considering a switch from python-memcached to pymemcache in our [oslo.cache][3] Memcache backend driver. In the next step, we will need to enable TLS in Memcached as data must be encrypted in the wire for our scenario.

I looked over the documentation and couldn't find anything related to TLS support. If there is a way to achieve that, please let us know.

I would like to help with the implementation of this if needed.

[1]: https://github.com/memcached/memcached/wiki/TLS
[2]: https://www.openstack.org/
[3]: https://opendev.org/openstack/oslo.cache

**Comment by jparise** [comment]
I don't believe anyone is working on TLS support so we'd gladly accept a contribution that implements it.

**Comment by moisesguimaraes** [comment]
Hi @jparise,

Thanks for reaching out!

We actually have backend drivers for multiple python memcached clients. We'll try to synchronize patches across all clients we use and try to merge the feedback reviews we get in all of them.

Here is our memcached python clients mapping so far:

## Oslo Cache Memcached Backends

### oslo_cache.memcache_pool
 - Underlying library: python-memcached
 - Feature request: https://github.com/linsomniac/python-memcached/issues/171
 - Possible future underlying library: pymemcache
 - Change: https://review.opendev.org/#/c/634457
 - Feature request: https://github.com/pinterest/pymemcache/issues/258

### dogpile.cache.memcached
  - Underlying library: python-memcached
  - Feature request: https://github.com/linsomniac/python-memcached/issues/171

### dogpile.cache.pylibmc
- Underlying library: pylibmc
- Feature request: https://github.com/lericson/pylibmc/issues/255

### dogpile.cache.bmemcached
  - Underlying library: python-binary-memcached
  - Feature request: https://github.com/jaysonsantos/python-binary-memcached/issues/207

**Comment by jparise** [comment]
Closed by #276

**Comment by moisesguimaraes** [comment]
Thanks for the reviews @jparise o/
