### ISSUE TITLE
No implementation for touch command in HashClient

### ISSUE THREAD

**Issue by alisaifee** [pinterest/pymemcache#263]
`pymemcache.client.hash.HashClient` doesn't implement the `touch` command while `pymemcache.client.base.Client` does. 

Is there a reason for this? If not, would you accept a pull request for adding the method?

**Comment by jparise** [comment]
I think that's just an oversight. We'd be happy to review a pull request that adds it.

**Comment by jparise** [comment]
Implemented by #264.
