### ISSUE TITLE
pool:Too many objects

### ISSUE THREAD

**Issue by pystd** [pinterest/pymemcache#267]
I use `PooledClient `and the value passed to `max_pool_size `is **16**.
33 threads use the same PooledClient object and encountered this problem.
What should I do?
> File "/usr/local/lib/python3.6/dist-packages/pymemcache/pool.py", line 71, in get
    self.max_size))
RuntimeError: Too many objects, 16 >= 16

**Comment by jogo** [comment]
https://pymemcache.readthedocs.io/en/latest/apidoc/pymemcache.client.base.html#pymemcache.client.base.PooledClient

Your pool is too small for the amount of concurrency that you have
