### ISSUE TITLE
Elasticache - random read/write issues Pooled/Hash Client to Elasticache

### ISSUE THREAD

**Issue by seahawks8** [pinterest/pymemcache#269]
Having some odd issues, and I have tried multiple clients.

- using Elasticache Memcached cluster with two nodes
- calling from a flask app, I get None values with PoolClient. With HashClient, it works most of the time. If I step through the code, it usually returns the value.

Writing using Thread, the pooled client is stable, but HashClient and Client hit bad file descriptor issues.

I am using serialization, and I have read all the best practices. I am at a loss for what could be causing these issues.

**Comment by jogo** [comment]
PooledClient is the only one that makes any promise of being thread safe, so assuming your test case is using threading  I would expect the other clients to break as you saw.

https://pymemcache.readthedocs.io/en/latest/apidoc/pymemcache.client.base.html#pymemcache.client.base.PooledClient

**Comment by seahawks8** [comment]
I am closing this issue. My solution was to just use pooled client on the instances I am threading, and to use hashclient on my other instances.

**Comment by seahawks8** [comment]
Just an update on this, the issue was that by default Elasticache uses Jenkins for hashing, I had to change it to murmur3.
