### ISSUE TITLE
Avoid using False to indicate server down in HashClient.get_many().

### ISSUE THREAD

**Issue by pope1ni** [pinterest/pymemcache#291]
I want to propose changing the [value used by `HashClient.get_many()` when `ignore_exc=True`](https://github.com/pinterest/pymemcache/blob/54eb398eab4c625bf3696701f27e2a285477e1f5/pymemcache/client/hash.py#L375-L377) so that it doesn't conflict with a value of `False` that may have intentionally been stored. We should use a sentinel object instead or consider removing this entirely.

I came upon this when working on django/django#13310.

**Comment by jparise** [comment]
I'm open to changing this. The current behavior was originally introduced in e1d4c420d08edb4943f4409553aed71eaf4ade53, for reference.

My instinct is to not set any value in the result dictionary when its client is unavailable. That would be backwards incompatible, but I think it would be safer than introducing a sentinel object that would require clients to explicitly check (also backwards incompatible).

**Comment by pope1ni** [comment]
> ...than introducing a sentinel object that would require clients to explicitly check (also backwards incompatible).

Agreed. It is somewhat moot as to whether it matters that a value cannot be found because the key didn't exist or because one of the clients was unavailable. If it is important to know that clients are missing, then don't use `ignore_exc=True`.

I'll try to create a pull request soon.
