### ISSUE TITLE
3.4.0 Regression with "localhost"

### ISSUE THREAD

**Issue by moisesguimaraes** [pinterest/pymemcache#303]
Our CI jobs started failing with the release of 3.4.0 and it had to be blacklisted in our requirements. My hypothesis is that "localhost:11211" is now translating the hostname to ::1 while the memcached server is listening on 127.0.0.1.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tooz/drivers/memcached.py", line 43, in _failure_translator
    yield
  File "/usr/local/lib/python3.8/dist-packages/tooz/drivers/memcached.py", line 70, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tooz/drivers/memcached.py", line 495, in heartbeat
    self.client.set(self._encode_member_id(self._member_id),
  File "/usr/local/lib/python3.8/dist-packages/pymemcache/client/base.py", line 1120, in set
    return client.set(key, value, expire=expire, noreply=noreply,
  File "/usr/local/lib/python3.8/dist-packages/pymemcache/client/base.py", line 378, in set
    return self._store_cmd(b'set', {key: value}, expire, noreply,
  File "/usr/local/lib/python3.8/dist-packages/pymemcache/client/base.py", line 968, in _store_cmd
    self._connect()
  File "/usr/local/lib/python3.8/dist-packages/pymemcache/client/base.py", line 336, in _connect
    sock.connect(sockaddr)
  File "/usr/local/lib/python3.8/dist-packages/eventlet/greenio/base.py", line 267, in connect
    socket_checkerr(fd)
  File "/usr/local/lib/python3.8/dist-packages/eventlet/greenio/base.py", line 51, in socket_checkerr
    raise socket.error(err, errno.errorcode[err])
ConnectionRefusedError: [Errno 111] ECONNREFUSED
```

**Comment by moisesguimaraes** [comment]
@pope1ni ^

**Comment by pope1ni** [comment]
The release note was updated to reflect this: aae4fe1bda9755f006a33b88f1589f29507996fc.

Can you not make memcached also listen on ::1 or change your connect string to 127.0.0.1? Ultimately this feels like a configuration issue, not a regression.

**Comment by elfosardo** [comment]
I believe this is a weird behavior on memcached or on the system side, I would expect memcached to listen to both ipv6 and ipv4 addresses if pointed to listen to localhost.
With that said, if we point memcached to 127.0.0.1 it will of course work, so it's a viable workaround.
One thing I can confirm is that it doesn't look like a regression on pymemcache itself at this point.

**Comment by moisesguimaraes** [comment]
I can confirm that `memcached -l localhost`, `memcached -l 127.0.0.1`, `memcached -l ::1` show different behavior. The one listening to `localhost` will bind to both interfaces.

**Comment by pope1ni** [comment]
> I believe this is a weird behavior on memcached or on the system side, I would expect memcached to listen to both ipv6 and ipv4 addresses if pointed to listen to localhost.

So I checked what I have locally as installed by default in `/usr/lib/systemd/system/memcached.service`:

```ini
...

[Service]
User=memcached
Environment=CACHESIZE=64
Environment=MAXCONN=1024
Environment=LISTEN="-l 127.0.0.1,::1"
Environment=OPTIONS="-o modern,drop_privileges"
ExecStart=/usr/bin/memcached -m ${CACHESIZE} -c ${MAXCONN} $LISTEN $OPTIONS

...
```

Looks like it explicitly listens to both IPv4 and IPv6 in my case, but it does need to be configured. If you're only listening to IPv4 and your system can resolve `localhost` to `::1` because IPv6 is supported and enabled, then it's a configuration issue. Use `127.0.0.1` when connecting if you want to force IPv4.

> One thing I can confirm is that it doesn't look like a regression on pymemcache itself at this point.

:+1:

**Comment by pope1ni** [comment]
> I can confirm that `memcached -l localhost`, `memcached -l 127.0.0.1`, and `memcached -l ::1` show different behavior. The one listening to `localhost` will bind to both interfaces.

That sounds completely sensible!

**Comment by jparise** [comment]
We also discussed this recently in #301, which highlights this documentation update:

https://github.com/pinterest/pymemcache/blob/9bf5dd5d6e4bf2d6de9d3b2778e55958a74474a9/docs/getting_started.rst#L37-L38

... and resulted in this #302, which brings more attention to this change in the changelog.

**Comment by moisesguimaraes** [comment]
We found a way to unblock our CI, thanks for chiming in for the discussion guys o/

**Comment by pope1ni** [comment]
> ...which highlights this documentation update...

I'm glad I did actually mention this in the documentation. Thanks @jparise for making it more prominent in the changelog.
