### ISSUE TITLE
Feature request:  Implement lru_crawler command?

### ISSUE THREAD

**Issue by keeely** [pinterest/pymemcache#308]
See: https://github.com/memcached/memcached/wiki/ReleaseNotes1431

I had a feeble attempt to subclass the client and add my own command, but I realised this is not such a good idea and I should probably leave it to the expert(s), so I wondered if you could add it?  Something like:

```
class MyClient(Client):
    def __init__(self):
        Client.__init__(self, ("127.0.0.1", MEMCACHE_PORT))

    def lru_crawler(self, *args):
        result = self._fetch_cmd(b'lru_crawler', args, True)
        out = []
        for value in result:
            out.append(value)
        return out
```

Didn't get to reading the results, I got this error:

```
    result = self._fetch_cmd(b'lru_crawler', args, True)
  File "/usr/local/lib/python3.8/site-packages/pymemcache/client/base.py", line 923, in _fetch_cmd
    raise MemcacheUnknownError(line[:32])
pymemcache.exceptions.MemcacheUnknownError:   <start of my first key here>
```

**Comment by cgordon** [comment]
It doesn't look like the existing helper functions would work for the various lru_crawler commands, so it would require a fair bit of programming and testing. We'd obviously be happy to get a contribution :)

**Comment by keeely** [comment]
Thanks for your response, unfortunately I'm only very briefly looking at memcached and will probably never need it after this week so can't justify the effort.
