### ISSUE TITLE
Does pymemcache has some limit of buffer size?

### ISSUE THREAD

**Issue by yakirsudry** [pinterest/pymemcache#317]
When using `django.core.cache.backends.memcached.MemcachedCache` in Django it is common to configure:

```
'OPTIONS': {
            'server_max_value_length': (1024 ** 2) * 4
        }
```

To modify the limit. Is that required when using PyMemcacheCache?

**Comment by jogo** [comment]
No, as far as I can tell pymemcache doesn't have any logic to test for server side max value length before sending requests to memcache
