### ISSUE TITLE
`HashClient.set_many` performs several single `set` commands

### ISSUE THREAD

**Issue by martinnj** [pinterest/pymemcache#319]
This is not strictly an issue, more of a clarification before I fork something and start working.

The current `HashClient.set_many()` function ends up performing `n` single `set` commands for `n` values, instead of performing `m` `set_many` commands for `m` number of `base.Client` in the `HashClient`. Assuming we run without the `PooledClient`.

The call chain goes `HashClient.set_many -> HashClient._safely_run_set_many -> HashClient._set_many -> base.Client.set`
My expectations would be that the end should be `base.Client.set_many` instead. The line in question: [L340](https://github.com/pinterest/pymemcache/blob/64109c2b140807d19cb65ce8f34ff0121b468fe3/pymemcache/client/hash.py#L340)

I was going to take a stab at implementing it that way but just wanted to hear if this had already been tried and scrapped, and if there was a specific reason for using sequential `set` commands instead of `set_many`?

**Comment by jogo** [comment]
Looks like `HashClient.set_many` wasn't updated to take advantage of https://github.com/pinterest/pymemcache/pull/182. So a pull request to update this would be great.
