### ISSUE TITLE
The client objects don't appear to be threadsafe.

### ISSUE THREAD

**Issue by harlowja** [pinterest/pymemcache#34]
It doesn't appear that the usage of the same socket (and/or client) by different threads is safe. It would be great to either mention that in the docs or make it thread safe.

A possible variation that I think makes this safe is @ https://review.openstack.org/#/c/173101/ (feel free to take that code or adjust it... as u want).

**Comment by harlowja** [comment]
Or a connect/socket pool (that is thread-safe) would be even better... that each call into a a command grabs/releases a socket from that pool (and therefore they can't overlap no matter what).

**Comment by cgordon** [comment]
I've commented in the PR on this, and agree that it warrants documentation, which I'll add once we've resolved the PR.
