### ISSUE TITLE
HashClient failover - How a node is automatically rebalanced when a node of cluster goes down?

### ISSUE THREAD

**Issue by 4383** [pinterest/pymemcache#359]
Hello everyone,

We've some questions regarding how the HashClient's failover mechanisms works and what we should expect when we use memcached cluster with pymemcache.

Here is an example of scenario.

We have 3 cluster nodes:

```
192.168.0.3:11211
192.168.0.4:11211
192.168.0.4:11211
```

We instantiate a HashClient by passing those nodes to the `servers` param.

This client is alive and the socket remains connected and live in an execution loop, we call `set` and `get` a couple of time, the client will communicate with one of these 3 servers accordingly to the the hash. While this server is up the client will use only this server. However at some point we kill all the 3 nodes and we restart only two nodes that aren't the server used by the client initialy, what do we should expect at this point?

Does the client will automatically switch the connection (by establishing a new socket) to one of these 2 servers and restart to set and get things from it?

Apparently, if we understand correctly your doc, [it said that yes, the server will be automatically rebalanced depending on if a server goes down](https://pymemcache.readthedocs.io/en/latest/getting_started.html#using-a-memcached-cluster).

Here is a sample of code that more or less summarize the previously described scenario:

https://github.com/4383/oslo.cache-labs/blob/master/labs/oslo.cache/pymemcache_backend/app.py
https://github.com/4383/oslo.cache-labs/blob/master/labs/oslo.cache/pymemcache_backend/lab/app.conf

This snippet of code rely on the stack [oslo.cache](https://review.opendev.org/c/openstack/oslo.cache/+/803747) / [dogpile.cache](https://github.com/sqlalchemy/dogpile.cache/commit/36390997c6350a606c7cabe4ea85dd05f4bddd52) / pymemcache

Our problem is that with this scenario we didn't observed the server switch within our client (either in this snippet or even in a more serious testing in openstack), so either we misundertood something or we missed something during our tests.

We'd expect to see the client mark this server as dead and switch the connection to another server that is up.
That's not what we observed.

Please can you give us more details about what we should expect with this scenario.

Thanks in advance.

**Comment by martinnj** [comment]
I think you might've misunderstood what `HashClient` does. 

`HashClient` will always try to distribute keys evenly on all given nodes using the `hasher` provided in the constructor. By default this is the built-in [Rendezvous hasher](https://github.com/pinterest/pymemcache/blob/master/pymemcache/client/rendezvous.py).

When you perform any operation involving a key, that key will be fed to the hasher, and that will decide what node corresponds to the key, and so, what node receives the command.

If a node is down, once the `HashClient` detects this it marks it as down, and any hashing going forward will hit a different node. After the `dead_timeout` [constructor parameter](https://github.com/pinterest/pymemcache/blob/master/pymemcache/client/hash.py#L44)  has expired, any dead node will be put back in, and attempted again.

If the client marks all servers as down, commands will return a `MemcacheError` [saying so](https://github.com/pinterest/pymemcache/blob/master/pymemcache/client/hash.py#L182).

To take a look at your example:
1) After calling `get`/`set` a couple of times, all three servers will have _some_ values stored on them.
2) Servers er reset/restarted.
3) If `Hashclient` tried working with them while they're down, it will not just give exceptions until the `dead_timeout` expires.
    If it didn't any commands will now hash to the same servers, any commands going to server 3 (down) will fail and then it will be marked as dead.
4) Any new `get`/`set` commands will go to server-1 & -2.
5) After `dead_timeout` expires, server-3 will come back in rotation, until it fails again.

Does that make sense? :)

**Comment by 4383** [comment]
Good write up. Thanks for your explanation.

**Comment by jparise** [comment]
@martinnj would you be interested in updating the `HashClient` documentation with some of the rich detail you've provided above?

**Comment by martinnj** [comment]
> @martinnj would you be interested in updating the `HashClient` documentation with some of the rich detail you've provided above?

Sure thing. :)
