### ISSUE TITLE
Why HashClient().flush_all does not have noreply argument?

### ISSUE THREAD

**Issue by halhorn** [pinterest/pymemcache#360]
I would be happy if flush_all in HashClient method has noreply argument.

On testing, I do flush_all on every test case by TestCase().tearDown() to clear each test state.
However, if default_noreply is True, the flush_all runs asynchronously so some tests fails.
Currently I set default_noreply False for testing but I think it is not best choice. I would be happy if I can set noreply=False on flush_all method in HashClient.

**Comment by jogo** [comment]
As best I can tell the answer to the question is it was never implemented (the original code didn't have it: 24705082a2792f771ee7a2f07a602eb1f59febf6)

**Comment by halhorn** [comment]
Thank you for https://github.com/pinterest/pymemcache/pull/361/ !
I'm happy!
