### ISSUE TITLE
Name 'basestring' is not defined (django error)

### ISSUE THREAD

**Issue by khajvahmac** [pinterest/pymemcache#43]
Using python 3.4.2 and django 1.7

Here is the traceback:

```Traceback:
File "C:\Python34\lib\site-packages\django\core\handlers\base.py" in get_response
  111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "C:\Users\User\Project\miraFrontEnd\manageDb\views.py" in mira_cacl
  329.     cache_chains.set(1 + cache_chains.get('count'), a, None)
File "C:\Python34\lib\site-packages\django\core\cache\backends\memcached.py" in set
  89.         self._cache.set(key, value, self.get_backend_timeout(timeout))
File "C:\Python34\lib\site-packages\pymemcache\client.py" in set
  335.         return self._store_cmd(b'set', key, expire, noreply, value)
File "C:\Python34\lib\site-packages\pymemcache\client.py" in _store_cmd
  749.             data, flags = self.serializer(key, data)
File "C:\Python34\lib\site-packages\djpymemcache\backend.py" in serialize_pickle
  27.     if isinstance(value, basestring):
Exception Type: NameError at /manageDb/mira/miracalc/
Exception Value: name 'basestring' is not defined
```

**Possible fix:**

I have added following lines in the beginning of ```\site-packages\djpymemcache\backend.py``` and it worked:

```
try:
    unicode = unicode
except NameError:
    # 'unicode' is undefined, must be Python 3
    str = str
    unicode = str
    bytes = bytes
    basestring = (str,bytes)
else:
    # 'unicode' exists, must be Python 2
    str = str
    unicode = unicode
    bytes = str
    basestring = basestring
```
*Note that I didn't write those lines. I took it from [here](https://github.com/oxplot/fysom/issues/1)*

**Comment by cgordon** [comment]
It looks like this is an issue with the djpymemcache library, which is here:

https://github.com/jsocol/django-pymemcache

You'll have to open an issue with them to get it fixed. They will need to change the line:

```
if isinstance(value, basestring):
```

to something like:

```
if isinstance(value, six.string_types):
````

That should make it compatible across Python 2 and 3, to the best of my knowledge (we don't use Python 3, so this is not an area in which I have much expertise).

I just noticed that we have a similar problem with our ```serde.py``` code, so I'll submit a separate fix for that.

**Comment by khajvahmac** [comment]
Awesome, thank you. And sorry for reporting in the wrong repo (should have done more research before posting this).

**Comment by cgordon** [comment]
No worries! Thanks for the report, I caught a bug in our code with it as well :)
