### ISSUE TITLE
Feature request: Pass hashed server value to get/set/delete functions (for example get_many to one hashed server)

### ISSUE THREAD

**Issue by matejsp** [pinterest/pymemcache#457]
Old unmaintained python-memcached supported passing tuple as a key to support selecting specific server.
https://github.com/linsomniac/python-memcached/blob/master/memcache.py#L114

I would like the same functionality for pymemcache to support calling functions on one specific server.

**Comment by jogo** [comment]
Sounds like a reasonable feature request. 

For anyone reading this, feel free to contribute this feature and we will gladly review and merge it.
