### ISSUE TITLE
Intermittent MemcacheUnknownCommandError for "lru_crawler metadump all"

### ISSUE THREAD

**Issue by josh-lexisnexis** [pinterest/pymemcache#469]
I am trying to get a list of all available keys from memcache and I am getting intermittent error when attempting to use function raw_command with "lru_crawler metadump all". Since I didn't see any function that already does this. 

-----------------------------------------------------------------------------------------------------------------------

OS: Ubuntu 22.04 LTS 
Memcache Server: localhost
Memcache Port: 11211

-----------------------------------------------------------------------------------------------------------------------

**Code:**
import re
import logging
import pymemcache
from pprint import pprint

class MEMCACHE:
  handler = ""
  server = ""
  port = ""

  def __init__(self, server=None, port=None):
    if server:
      self.server = server
    if port:
      self.port = port
    self.handler = self.connect(self.server, self.port)

  def connect(self, server, port):
    logging.info("Connecting to Memcache Server: %s on %s" % (server, port))
    return pymemcache.client.base.Client((server, port))

  def list(self):
    res = []
    raw_data = b""
    raw_data = self.handler.raw_command("lru_crawler metadump all")
    raw_data = raw_data.decode("utf-8")
    raw_data = re.split("[\n\ =]", raw_data)
    for each in range(0, len(raw_data)):
      if raw_data[each] == "key":
        each += 1
        res.append(raw_data[each])
    return res

if __name__ == "__main__":
  memoryCache = MEMCACHE("localhost", 11211)
  pprint(memoryCache.list())

-----------------------------------------------------------------------------------------------------------------------

**Example of Intermittent Output:**
nagios@nagios-test:~/monitoring-python-classes$ python memcache_class.py 
['SuperDuperTest1', 'SuperDuperTest2', 'SuperDuperTest3']

nagios@nagios-test:~/monitoring-python-classes$ python memcache_class.py 
Traceback (most recent call last):
  File "/home/nagios/monitoring-python-classes/memcache_class.py", line 61, in <module>
    pprint(memoryCache.list())
  File "/home/nagios/monitoring-python-classes/memcache_class.py", line 36, in list
    raw_data = self.handler.raw_command("lru_crawler metadump all")
  File "/usr/local/lib/python3.10/dist-packages/pymemcache/client/base.py", line 967, in raw_command
    return self._misc_cmd([b"" + command + b"\r\n"], command, False, end_tokens)[0]
  File "/usr/local/lib/python3.10/dist-packages/pymemcache/client/base.py", line 1295, in _misc_cmd
    self._raise_errors(line, cmd_name)
  File "/usr/local/lib/python3.10/dist-packages/pymemcache/client/base.py", line 1034, in _raise_errors
    raise MemcacheUnknownCommandError(name)
pymemcache.exceptions.MemcacheUnknownCommandError: b'lru_crawler metadump all'

**Comment by jogo** [comment]
I am unable to reproduce the issue locally. (Assuming I re-formatted your sample correctly).

`_raise_errors` will raise `pymemcache.exceptions.MemcacheUnknownCommandError` when memcached throws that error. So it might be useful to run memcached with the `-vv` flag to see what is being sent etc.

**Comment by josh-lexisnexis** [comment]
Ran the memcached with -vv and below is the error response from memcached. 

<23 lru_crawler metadump all
>23 ERROR cannot pipeline other commands before metadump

I think I may have found another way to get the data without using "lru_crawler metadump all".

**Comment by josh-lexisnexis** [comment]
Created a work-around by using subprocess to call the memcache-dump or memcdump command. Not ideal, but it gets the job done. 

Thanks for looking into this.
