### ISSUE TITLE
How to properly set the `timeout` and `connect_timeout` values?

### ISSUE THREAD

**Issue by yuanzhou** [pinterest/pymemcache#473]
I'm using a pooled connection client (uWSGI with multi-threading and multi-processing) against the Memcached cluster running on AWS and trying to understand how to properly set the `timeout` and `connect_timeout` values. The documentation doesn't say much about these two parameters.

Currently I have the below working client, but wanted to know if I should increase the `timeout` and `connect_timeout` values. I chose to use `connect_timeout = 1` because any bigger value will result a delay when I start up the python app for the first time (causing a noticeable blocking). I don't know if the `timeout` setting is for creating a new connection when all the pooled connections are in use.
```
memcached_client_instance = PooledClient(app.config['MEMCACHED_SERVER'], 
                                         max_pool_size = 8,
                                         connect_timeout = 1,
                                         timeout = 30,
                                         ignore_exc = True, 
                                         no_delay = True,
                                         serde = serde.pickle_serde)
```
Any suggestions are greatly appreciated!

**Comment by jogo** [comment]
Posted a PR to include the right information in the docs, in this case this It's the docstrings fro the __init__ function

https://github.com/pinterest/pymemcache/blob/2ea9a9e027f19f21e658cacc286b39ec1e59e887/pymemcache/client/base.py#L300
