### ISSUE TITLE
MacOS X 10.11 Issue

### ISSUE THREAD

**Issue by loretoparisi** [pinterest/pymemcache#48]
When installed on MacOS X 10..11

```
macbookproloreto:pymemcache admin$ python setup.py nosetests
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'nosetests
```

**Comment by cgordon** [comment]
@loretoparisi I cannot reproduce this issue on my Macbook Pro, even with a fresh checkout and no virtualenv. That means I probably have some package installed that you don't, or a package version that you don't. I'm not sure how to debug that without access to your laptop! Any ideas? Have you tried updating to the latest version of setuptools? Maybe that's part of it?

**Comment by methane** [comment]
@loretoparisi 
```console
$ https://bootstrap.pypa.io/get-pip.py
$ sudo python get-pip.py
$ sudo pip install nose
```

**Comment by methane** [comment]
@cgordon There are two ways to invoke nose from setup.py.
[setup.py test](http://nose.readthedocs.org/en/latest/setuptools_integration.html) and
[setup.py nosetests](http://nose.readthedocs.org/en/latest/api/commands.html).

In later case, `tests_require` is not installed.  nose should be installed before invoking setup.py.

**Comment by cgordon** [comment]
@methane is it worth adding nose to `setup_requires`, in addition to `tests_require`?

**Comment by methane** [comment]
@cgordon Yes. But it requires nose for just installing pymemcache.
I recommend to adding `test_suite = 'nose.collector'` and use `setup.py test` instead of `setup.py nosetests`.

**Comment by loretoparisi** [comment]
@methane yes I was the `nose` package missing. thank you.

**Comment by cgordon** [comment]
@methane Thanks for the explanation! That's very helpful. I'm going to add the "test_suite" option you recommended.
