### ISSUE TITLE
Add support for a pluggable consistent hashing system

### ISSUE THREAD

**Issue by sontek** [pinterest/pymemcache#52]
Options:

1. https://pypi.python.org/pypi/hash_ring
2. https://github.com/RJ/ketama/tree/master/python_ketama
3. https://github.com/ewdurbin/clandestined-python

Ketama is the one that `pylibmc` supports but since the protocols between the clients aren't 100% compatible there isn't any reason to completely follow their lead.

**Comment by sontek** [comment]
After doing a bunch of testing I've decided to go with clandestined.  It uses a C extension for the murmur3 consistent hashing algorithm which is pretty much necessary for performance requirements but I think its fine.

My test with 10,000 keys, this distribution looks like this:

![crc32](https://cloud.githubusercontent.com/assets/151924/8268809/63a3da04-1744-11e5-9f76-827776864ed3.png)
![ketama](https://cloud.githubusercontent.com/assets/151924/8268810/63a97338-1744-11e5-9c8c-996e27f47f21.png)
![murmur3](https://cloud.githubusercontent.com/assets/151924/8268811/63ab2caa-1744-11e5-8b0b-a993cea0fabd.png)

You can see using HRW (Rendezvous) balancing with a Murmur3 hash we are able to prevent any hotspots and evenly distribute the keys across all our servers.

I also checked how many keys would have to be redistributed if we dropped off on server and get the following:

```
CRC3 Redistribution 51.04
Murmur3 Redistribution 50.3
Ketama Redistribution 59.8
```

Murmur3 had the most evenly distributed keys and had to rebalance the lease amount.  Ketama (which is what pylibmc uses) has the worst amount of hotspots and has to redistribute the most.

**Comment by duanhongyi** [comment]
Code LGTM.
