### ISSUE TITLE
Add support for pluggable compression

### ISSUE THREAD

**Issue by sontek** [pinterest/pymemcache#53]
By default memcached has a 1mb limit and when you are working with larger objects using compression can get you a lot of additional caching for little overhead.

Primary cache algorithms that should be supported:
1. lz4
2. speedy
3. zlib

The compression shouldn't kick in automatically, we should have a sane threshold for when compression starts

**Comment by harlowja** [comment]
What python library provides all of those?

**Comment by sontek** [comment]
You don't need a single python library for them.  i.e if you allow this:

```
class ICompressable:
    def compress(obj):
        pass
    def decompress(obj):
        pass
```

and on the client you accept a `compressor` argument:
```
from pymemcache import Client
import lz4

class LZ4Compressor:
    def compress(obj):
        return lz4.dumps(obj)

    def decompress(obj):
        return lz4.loads(obj)
         
client = Client(compressor=lzr_compressor)
```

**Comment by harlowja** [comment]
Fair enough that works to.

**Comment by sontek** [comment]
Only thing would be if we wanted to flag each type of compressor in the data that way if you had two clients:

```
client = Client(compressor=lz4_compressor)
client2 = Client(compressor=speedy_compressor)
```

If client1 tried to open a key from client2 it would fail.  Would we want to detect its using a different compressor and raise a nice error like "Hey, that key was compressed with lz4!" or do we just blow up with a weird error and let them figure it out?

If we wanted to provide the nice flags then we'd have to maintain them internally like:

```
FLAG_LZ4 = 1 << 3
FLAG_SPEEDY = 1 <<  4
FLAG_ZLIB = 1 << 5
```

**Comment by akatrevorjay** [comment]
I put up a refactor branch to help with this in #160 and #161 along with a json codec. I wrote something similar for my own projects in the past, so it was mostly copypasta from that. I need to dig deeper but I also have a pipeline that would be helpful in this case, ie compression. We can just pass the bitflags in modified, that's at least what I did in the past.

**Comment by jparise** [comment]
Closing this because this functionality is now available through the `serde` object interface.
