### ISSUE TITLE
Add documentation for `PooledClient`

### ISSUE THREAD

**Issue by sontek** [pinterest/pymemcache#57]
Document how/when you would use `PooledClient` vs standard `Client`

**Comment by sontek** [comment]
We have module docs for this on readthedocs now:

http://pymemcache.readthedocs.org/en/latest/apidoc/pymemcache.client.html#pymemcache.client.base.PooledClient

So we can just improve the docs there and then maybe just add a blurb in getting started about it.

**Comment by nichochar** [comment]
+1 completely agree. Feel free to make a PR for this particular part of the docs, I will be adding docs as mentioned in https://github.com/pinterest/pymemcache/issues/102

Closing this as it is a dupe of that ticket.
Thanks!
