### ISSUE TITLE
Make set_multi/get_multi that map to  set_many/get_many 

### ISSUE THREAD

**Issue by sontek** [pinterest/pymemcache#58]
set_multi/get_multi are the standard naming for these and would be nice to be consistent with the other available clients.

**Comment by sontek** [comment]
Outside of the `set_many` and `get_multi` API changes I think we should try to match the API so that this client is interchangeable with python-memcached and pylibmc

**Comment by adamchainz** [comment]
+1 makes it easier to integrate with django's cache backends

**Comment by adamchainz** [comment]
Also `delete_multi`
