### ISSUE TITLE
Release on PyPI

### ISSUE THREAD

**Issue by adamchainz** [pinterest/pymemcache#67]
Problems with github-only pip packages:

* `pip install -r requirements.txt` is slower - the git package must always be fetched even in the case of no change. I use the tarball syntax (`https://github.com/pinterest/pymemcache/archive/642c094aa561e99125dd9955670b65974ea6b16b.tar.gz`) which is a bit faster since it bypasses git but it's still slower since it's not a version compare
* No wheels, no caching - especially relevant with the pip 7 changes to wheel caching - all the PyPI-based packages are cached in my build pipeline and take milliseconds to install
* No versions - often an incremental upgrade won't be installed because pip sees the version in `setup.py` as being the same. Also as I user I have to just "trust" that a commit is safe, whereas a released version is an indicator of a bit more thought.

Please put releases on PyPI with universal wheels :)

**Comment by thedrow** [comment]
You can also setup travis to release to PyPi for you when you tag a commit which is very useful since it forces you to tag the release as well. Otherwise people forget.

**Comment by cgordon** [comment]
I thought I had been releasing universal wheels to pypi, for instance:

https://pypi.python.org/pypi/pymemcache/1.2.9

There is code in this repository that I have not yet released, as we are currently testing it internally. It looks good so far, and I expect to be releasing the latest code this weekend.

That said, I'm a beginner at all things related to releasing packages (pip/setuptools/wheels/etc), and have been just following instructions given to me by other people, without clearly understanding them. I have been looking around and found this checklist for releasing packages:

https://gist.github.com/audreyr/5990987

I'm planning to do this for every release from here forwards. Does that do what you want?

**Comment by adamchainz** [comment]
Everything apart from the Readme saying its on pip :) I had no idea since I
only came across the GitHub page.

On Thursday, 23 July 2015, Charles Gordon <notifications@github.com> wrote:

> I thought I had been releasing universal wheels to pypi, for instance:
>
> https://pypi.python.org/pypi/pymemcache/1.2.9
>
> There is code in this repository that I have not yet released, as we are
> currently testing it internally. It looks good so far, and I expect to be
> releasing the latest code this weekend.
>
> That said, I'm a beginner at all things related to releasing packages
> (pip/setuptools/wheels/etc), and have been just following instructions
> given to me by other people, without clearly understanding them. I have
> been looking around and found this checklist for releasing packages:
>
> https://gist.github.com/audreyr/5990987
>
> I'm planning to do this for every release from here forwards. Does that do
> what you want?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pinterest/pymemcache/issues/67#issuecomment-124170857>
> .
>


-- 
Adam

**Comment by cgordon** [comment]
Cool, send me a PR to add pip installation instructions to the readme and all is forgiven ;)

**Comment by adamchainz** [comment]
PR written!

Looks like a pip release hasn't been done since April, that's 72 commits: https://github.com/pinterest/pymemcache/compare/v1.2.9...master

Also the README is broken on the PyPI page, that's because it only supports restructured text and not the markdown that was uploaded. You can fix this by just running `python setup.py register` again.

**Comment by cgordon** [comment]
Yep, I'm planning to do a release this weekend. I didn't realize you needed to do a register to update the README, thanks!
