### ISSUE TITLE
Fix the description on PyPi

### ISSUE THREAD

**Issue by cgordon** [pinterest/pymemcache#70]
After release 1.3.0 the description on PyPi is showing raw restructured text instead of a well formatted HTML page:

https://pypi.python.org/pypi/pymemcache/1.3.0

It isn't clear to me why that is happening. I have run the README.rst file through rst2html, and it gives a couple minor warnings, but renders correctly.

**Comment by methane** [comment]
> it gives a couple minor warnings,

It's enough to fallback to plain text on PyPI.

**Comment by cgordon** [comment]
Thanks @methane, I was starting to wonder if that was the case. I will fix the warnings and run `python setup.py register` again.

**Comment by methane** [comment]
`python setup check -rs` may help you.

```console
$ python setup.py check -rs
running check
error: The docutils package is needed.
$ pip install docutils
Successfully installed docutils-0.12
$ python setup.py check -rs
running check
warning: check: Title underline too short. (line 115)

error: Please correct your package.
$ echo $?
1
```

**Comment by cgordon** [comment]
Alright, fixing the warning in rst2html seems to have solved the problem on pypi, thank you for your help @methane!
