### ISSUE TITLE
Client will set values it can't deserialize

### ISSUE THREAD

**Issue by sontek** [pinterest/pymemcache#82]
It documents that values should be strings but it doesn't actually prevent you from doing something like:

``` python

client.set(b'key', ('boom, 'shaka', {'1': 'two'}))
```

**Comment by sontek** [comment]
Should we just default to using the serializers from `serde`?

**Comment by nichochar** [comment]
@sontek it was my understanding that that was the functionality. I think that defaulting to using `serde` would be good, yes. We can make it a kwarg with the `serde` default. 

Let's make this change once the python3 version of `serde` is shipped, which should be https://github.com/pinterest/pymemcache/pull/112

**Comment by jogo** [comment]
Current behavior.

```
>>> from pymemcache.client.base import Client
>>> client = Client(('localhost', 11211))
>>> client.set(b'key', ('boom', 'shaka', {'1': 'two'}))
True
>>> client.get(b'key')
"('boom', 'shaka', {'1': 'two'})"
```

@sontek I am unclear on what expected behavior you would like to see here.  Closing this ticket for now, but feel free to re-open with more information.

**Comment by sontek** [comment]
@jogo I think we should leave this open, your snippet shows exactly the behavior I'm complaining about.  You are getting back something you didn't pass in:

Tuple of objects:
```
('boom', 'shaka', {'1': 'two'})
```

Bytes:
```
b"('boom', 'shaka', {'1': 'two'})"   
```

If you are using the client and you pass in a dictionary, tuple, etc you are going to expect that same type back.

**Comment by sontek** [comment]
(I don't have privileges to re-open)

**Comment by nichochar** [comment]
What are suggestions for fixing here?
I can think of 2:
- return an error if you try and pass a non string (this would probably break a bunch of people's usages)
- serialize and deserialize always by default, which affects performance.

@sontek do you have any thoughts on these solutions, or any other?

**Comment by sontek** [comment]
I would suggest doing serialize/deserialize.  Since `serde.py` is using flags to mark the content I don't think there would be a big performance hit would there?  It would know if it needs to deserialize coming back and its already serializing on the way there (to bytes).

**Comment by jogo** [comment]
@sontek I don't think that would work, for example:

```
>>> a = object()
>>> a
<object object at 0x107314e30>
>>> client.set(b'key', a)
True
>>> client.get(b'key')
'<object object at 0x107314e30>'
```

The return value doesn't have enough information to recreate the original object.

**Comment by sontek** [comment]
@jogo Thats why we would user serialization to have enough information.  This can be done with `jsonpickle`, `pickle`, `msgpack`, etc.

**Comment by sontek** [comment]
I guess since there are already `args` for `serializer` and `deserializer` maybe the best option is to just reject the values we can' store properly and tell them to set a serializer?

**Comment by jogo** [comment]
@sontek that's what I am thinking, I am weary of silently adding in a serializer like this. I think manually setting a serializer for this makes more sense. As for the default behavior, I am little weary of changing it so perhaps for now we can add a flag to change the behavior and re-visit making it the default down the road.

**Comment by jogo** [comment]
After thinking about this further, I don't think we should change the current default behavior. The current behavior is documented.

http://pymemcache.readthedocs.io/en/latest/apidoc/pymemcache.client.base.html

We can add a no-op serializer that will reject values that aren't already serialized.

Closing ticket for now, but if you would like I can make it easier to avoid this issue or clarify the documentation etc.
