### ISSUE TITLE
Should get pymemcache added as a supported backend to dogpile.cache

### ISSUE THREAD

**Issue by sontek** [pinterest/pymemcache#83]
dogpile.cache is a very popular way to interact with cache in python and some people might choose their memcached backend specifically based on what it supports so we should do our best to have good support inside it as well.

I've done the initial implementation here, its not perfect but I've run out of time for the weekend =)

https://bitbucket.org/zzzeek/dogpile.cache/pull-requests/34/this-gives-initial-support-for-pymemcache/diff

**Comment by jogo** [comment]
@sontek dogpile.cache support would be great, I noticed the pull request hasn't changed in a while.

Closing this ticket since it's more of a request for dogpile.cache
