### ISSUE TITLE
python_memcache_(de)serializer is python2 only

### ISSUE THREAD

**Issue by jjmurre** [pinterest/pymemcache#84]
pymemcache is python3 compliant, however, the serializer/deserializer in serde.py is python2 only.

**Comment by cgordon** [comment]
I don't use Python 3 (someone else converted pymemcache to python 3), so I'm not familiar enough to know what is broken about serde.py. Can you give me more specifics?

**Comment by jjmurre** [comment]
The main problem was the StringIO (needs to be BytesIO for python3) and the fact that integer and long have been unified in python3. I did not have time to create a version that supports both python2 and python3. 
A working implementation for python3 is:

import logging
import pickle
from io import BytesIO


FLAG_PICKLE = 1 << 0
FLAG_INTEGER = 1 << 1


def python_memcache_serializer(key, value):
    flags = 0

    if isinstance(value, bytes):
        pass
    elif isinstance(value, int):
        flags |= FLAG_INTEGER
        value = "%d" % value
    else:
        flags |= FLAG_PICKLE
        output = BytesIO()
        pickler = pickle.Pickler(output, 0)
        pickler.dump(value)
        value = output.getvalue()

    return value, flags


def python_memcache_deserializer(key, value, flags):
    if flags == 0:
        return value

    if flags & FLAG_INTEGER:
        return int(value)

    if flags & FLAG_PICKLE:
        try:
            buf = BytesIO(value)
            unpickler = pickle.Unpickler(buf)
            return unpickler.load()
        except Exception:
            logging.info('Pickle error', exc_info=True)
            return None

    return value

**Comment by nichochar** [comment]
I'm pretty sure https://github.com/pinterest/pymemcache/pull/112 fixes this. I will make sure once it's merged, and close accordingly.

**Comment by adamchainz** [comment]
#112 did indeed fix this
