### ISSUE TITLE
Wheel for 1.3.3 includes spurious client.py

### ISSUE THREAD

**Issue by davidblewett** [pinterest/pymemcache#85]
I was looking at the installed version of 1.3.3 (installed via pip 1.5.6) in a virtualenv. It picked the wheel file ( pymemcache-1.3.3-py2.py3-none-any.whl ). It appears that this file has a pymemcache/client.py as well as a pymemcache/client/ dir:

    riva% unzip pymemcache-1.3.3-py2.py3-none-any.whl 
    Archive:  pymemcache-1.3.3-py2.py3-none-any.whl
      inflating: pymemcache/__init__.py  
      inflating: pymemcache/client.py    
      inflating: pymemcache/exceptions.py  
      inflating: pymemcache/fallback.py  
      inflating: pymemcache/pool.py      
      inflating: pymemcache/serde.py     
      inflating: pymemcache/client/__init__.py  
      inflating: pymemcache/client/base.py  
      inflating: pymemcache/client/hash.py  
      inflating: pymemcache/client/murmur3.py  
      inflating: pymemcache/client/rendezvous.py  
      inflating: pymemcache/test/__init__.py  
      inflating: pymemcache/test/benchmark.py  
      inflating: pymemcache/test/conftest.py  
      inflating: pymemcache/test/integration.py  
      inflating: pymemcache/test/test_benchmark.py  
      inflating: pymemcache/test/test_client.py  
      inflating: pymemcache/test/test_client_hash.py  
      inflating: pymemcache/test/test_integration.py  
      inflating: pymemcache/test/test_rendezvous.py  
      inflating: pymemcache/test/test_utils.py  
      inflating: pymemcache/test/utils.py  
      inflating: pymemcache-1.3.3.dist-info/DESCRIPTION.rst  
      inflating: pymemcache-1.3.3.dist-info/metadata.json  
      inflating: pymemcache-1.3.3.dist-info/pbr.json  
      inflating: pymemcache-1.3.3.dist-info/top_level.txt  
      inflating: pymemcache-1.3.3.dist-info/WHEEL  
      inflating: pymemcache-1.3.3.dist-info/METADATA  
      inflating: pymemcache-1.3.3.dist-info/RECORD

In testing, it appears that at least PyPy 2.6.0 prefers the module instead of the file, but it would be good to double-check the packaging steps to ensure it's not accidentally included any more.

**Comment by cgordon** [comment]
That's bizarre, thanks for letting me know. I'll be packaging up a new release this weekend, and I'll double check that the spurious client isn't there. We recently switched from client.py to client/*.py, so it's possible I just failed to clean out an old directory somewhere.
