### ISSUE TITLE
how to get keys list which are older than 60 seconds

### ISSUE THREAD

**Issue by shashiranjansiso** [pinterest/pymemcache#91]
How my requirement is get all the keys that are older than 60 seconds. Is there any way I can get all the keys that are older than 60 seconds. One way i can think of is set the timeout and then check for each key if is expired. But can we set the timeout in pymemcache and check if item is expired? but in this case also i have to go through each key and check which is very costly. Can you suggest any better way?
Thanks,
Shashi

**Comment by adamchainz** [comment]
Memcached itself doesn't support key scanning like this (except slowly for debugging purposes), `pymemcache` can do nothing to help you there really.
