### ISSUE TITLE
stats value for evictions is boolean when it should be numeric?

### ISSUE THREAD

**Issue by amcrn** [pinterest/pymemcache#94]
per https://github.com/memcached/memcached/blob/b1debc4c96134e9014a929c32d6990cb5d66a22c/doc/protocol.txt#L562-L563 the value for `evictions` from a `stats` command is numeric.

but pymemcache is treating it as on/off: https://github.com/pinterest/pymemcache/blob/aac032419e94b5f71e763c130d54d4b6f36caa17/pymemcache/client/base.py#L56

this seems odd, because if memcached returns `evictions` as `55`, pymemcache is returning this as `False`.

i'd send a pull request, but it seems like this might have done for a reason that's escaping me at the moment ;) let me know.

**Comment by cgordon** [comment]
That looks like a bug, thanks for the report! If you have time to put together a pull request that would be great. Otherwise I'll add it to my to-do list :)

**Comment by rsanr** [comment]
@cgordon I work with @amcrn and will issue a pull request soon.
