### ISSUE TITLE
Security issue in input handling

### ISSUE THREAD

**Issue by homakov** [pinterest/pymemcache#99]
Key is not sanitized and something like \r\nflush_all\r\n in it could destroy all values and maybe more, if it comes from any user input.

**Comment by nichochar** [comment]
@homakov : Have you verified this?
Can you give some reproducible steps to destroy all values? I don't see how unsanitized input would ever be executed, and have not managed to reproduce this. 

I tried 
```python
>>> from pymemcache.client import Client
>>> client  = Client(('localhost', 11211))
>>> client.set('hello', 'world')
>>> client.set('safe', ' \r\nflush_all\r\n')
>>> print client.get('hello')
world
```

**Comment by homakov** [comment]
@nichochar try inserting in key, not the value.

**Comment by nichochar** [comment]
Indeed @homakov I was able to reproduce. Thank you for reporting this.

I am not a security expert, what are some good sanitization standards (or example) that you recommend?
